name: cham_card
description: A flashcard app for learning words.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.11.0
  flutter_local_notifications: ^19.2.0

flutter:
  uses-material-design: true
  assets:
    - flet_app/assets/BNazanin.ttf